### PR TITLE
Scan build analyzer fixes

### PR DESCRIPTION
**Pull request by kaworu**
Small fixes found by clang's static analyzer, I'll host the report at https://balin.enospoon.net/scan-build-2016-06-02-101836-28676-1/index.html until this PR gets merged or nuked :)

### CODE REVIEW

**Comment by kristapsdz** [comment]
I'm not sure if the strdup one is correct.  There's no manpage for X509V3_EXT_conf_nid, so I don't know whether it does anything with that pointer.  The "official" example uses of the function, e.g., [mkcert.c](https://github.com/libtor/openssl/blob/master/demos/x509/mkcert.c), suggest that the memory isn't touched or the behaviour would be undefined as it operates on string literals.  If you can get sign-off that X509V3_EXT_conf_nid doesn't abuse the string, then we can drop the strdup entirely, which is much better.  The rest have been fixed and will soon be pushed to GH.  Thank you!

**Comment by kaworu** [comment]
Not 100% sure either, but I've seen several examples on the web (like the first google result here http://stackoverflow.com/questions/2883164/openssl-certificate-lacks-key-identifiers) using string literal as "value".

I think the `strdup(3)` is a necessary evil since `X509V3_EXT_conf_nid` expect `char *` while `value` is `const char *` in the scope.

**Comment by kristapsdz** [comment]
Hm... the original string ("sans", constructed from line 194) could be passed into that as its original "char *" then just not freed (i.e., set to NULL after add_ext's successful return).  That removes a single strdup, but really just shuffles around the problem.  If you're up to asking on the openssl mailing list, they can hopefully demystify.  That whole X509_EXTENSION block is basically opaque.  But thanks for the other fixes!  They've all been merged.

**Comment by kaworu** [comment]
Thanks !

FYI From http://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/src/lib/libssl/src/doc/openssl.txt?rev=1.5&content-type=text/plain (which is as close as an "official" documentation can get I guess):

```
X509_EXTENSION *X509V3_EXT_conf_nid(char *conf, X509V3_CTX *ctx, int nid,
                                 char *value);

This function creates an extension in the same way as X509V3_EXT_conf() but
takes the NID of the extension rather than its name.

For example to produce basicConstraints with the CA flag and a path length of
10:

x = X509V3_EXT_conf_nid(NULL, NULL, NID_basic_constraints,"CA:TRUE,pathlen:10");
```

**Pull request closed without merging**
